import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    /// Crypto bridge blockchain technology
    func borderRexos() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }
}