import SwiftUI

// Generated by Supernova - do not modify manually
extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        /// Crypto bridge blockchain technology
        let rexos = Color(.sRGB, red: 14/255, green: 9/255, blue: 165/255, opacity: 1) 
    }
}