import SwiftUI

// Generated by Supernova - do not modify manually
extension Text {

    /// Crypto bridge blockchain technology
    func textStyleRexos() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 12))
    }
}
