import SwiftUI

// Generated by Supernova - do not modify manually
extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {

        /// Crypto bridge blockchain technology
        let rexos = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )
    }
}