import SwiftUI

// Generated by Supernova - do not modify manually
extension View {  

    /// Crypto bridge blockchain technology
    func borderRexos() -> some View {
        return self.cornerRadius(0) 
    }
}