import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    /// Crypto bridge blockchain technology
    func shadowRexos() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), radius: 0, x: 0, y: 0) 
    }
}